# Generated by Django 4.1.3 on 2023-01-09 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Джанго юзер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ActivateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код активации')),
                ('type', models.IntegerField(choices=[(1, 'Активация аккаунта'), (2, 'Восстановление пароля')], verbose_name='Тип кода')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован?')),
                ('expired_date', models.DateTimeField(verbose_name='Срок годности')),
                ('activated_date', models.DateTimeField(default=None, null=True, verbose_name='Дата активации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Код пользователя',
                'verbose_name_plural': 'Коды пользователя',
                'db_table': 'user_codes',
            },
        ),
    ]
