# Generated by Django 4.1.3 on 2023-01-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_users',
        ),
    ]
