# Generated by Django 4.1.3 on 2023-01-10 01:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_banned_until_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banned_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.JSONField(default=users.models.user_ban_json, verbose_name='Информация о бане'),
        ),
    ]
