# Generated by Django 4.1.5 on 2023-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStateCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='secret code')),
                ('ip', models.GenericIPAddressField(verbose_name='user ip')),
                ('expires', models.DateTimeField(verbose_name='session')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Привязаный вк'),
        ),
    ]
