# Generated by Django 4.1.5 on 2023-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_socialstatecodes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Привязаный вк'),
        ),
    ]
