# Generated by Django 4.1.5 on 2023-02-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_profile_vk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_redirected',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов пользователей по ссылкам за день'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_redirects',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов по ссылкам за день'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_redirected',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов пользователей по ссылкам'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_redirects',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов по ссылкам'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Привязаный вк'),
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок оповещения')),
                ('text', models.TextField(blank=True, verbose_name='Текст оповещения')),
                ('action', models.IntegerField(choices=[(0, 'Переадресация'), (1, 'Подтверждение')], default=0, verbose_name='Тип действия')),
                ('action_content', models.CharField(blank=True, max_length=999, verbose_name='Контент действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
