# Generated by Django 4.1.5 on 2023-02-11 01:09

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userrewards_profile_avatar_profile_bio_profile_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Последний IP адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний раз в сети'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rewards',
            field=models.ManyToManyField(to='users.userrewards', verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/default/img/no-avatar.jpg', upload_to=users.models.Profile.get_file_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Никнейм на сайте'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='Привязаный вк'),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='Айпи')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во входов')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Профиль')),
            ],
        ),
    ]
