# Generated by Django 4.1.5 on 2023-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_usernotifications_user_profile_last_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='Привязанный тг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Последний IP адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последний раз в сети'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='users.userrewards', verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='Привязанный вк'),
        ),
    ]
