version: '3.8'

services:
  # redis
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis

  #  postgres db
  postgres_db:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./django_hyperlink/.env
    container_name: postgres_db
    ports:
      - "5432:5432"

  # migrations
  django-migrate:
    build: .
    volumes:
      - .:/app/
    image: docker-app:django
    container_name: django-migrate
    command: python manage.py migrate
    depends_on:
      - postgres_db

#  django-collectstatic:
#    build: .
#    volumes:
#      - .:/app/
#    image: docker-app:django
#    container_name: django-collectstatic
#    depends_on:
#      - postgres_db
#      - django-migrate
#    command:
#      - python
#      - manage.py
#      - collectstatic
#      - --noinput

  # django app
  django:
    build: .
    volumes:
      - .:/app/
    ports:
      - "80:8000"
    image: docker-app:django
    container_name: django
    depends_on:
      - postgres_db
      - django-migrate
    env_file:
      - ./django_hyperlink/.env

  #  celery
  celery:
    restart: always
    build: .
    command:
     - celery
     - -A
     - django_hyperlink.celery_app
     - worker
     - --loglevel=INFO
     - --without-gossip
     - --without-mingle
     - --without-heartbeat
     - -Ofair
    volumes:
      - .:/app/
    container_name: celery
    depends_on:
      - postgres_db
      - redis
      - django

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5454:5454/tcp"
    env_file:
      - ./django_hyperlink/.env
    depends_on:
      - postgres_db

volumes:
  pgdata:
