# Generated by Django 4.1.5 on 2023-02-05 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='is_sharable',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная?'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='allowed_redirects',
            field=models.IntegerField(default=-1, verbose_name='Максимум редиректов'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата созания'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='redirect_timer',
            field=models.PositiveIntegerField(choices=[(0, 'Моментально'), (3, '3 секунды'), (5, '5 секунд'), (10, '10 секунд'), (15, '15 секунд')], default=5, verbose_name='Время до редиректа'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='redirect_to',
            field=models.URLField(verbose_name='Куда ведет ссылка'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='redirects',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество редиректов'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(editable=False, max_length=30, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='valid_until',
            field=models.DateTimeField(default=None, null=True, verbose_name='Истекает'),
        ),
    ]
