# Generated by Django 4.1.5 on 2023-02-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_remove_sharelink_is_sharable_sharelink_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharelink',
            options={'verbose_name': 'Сокращенная ссылка', 'verbose_name_plural': 'Сокращенные ссылки'},
        ),
        migrations.AlterModelTable(
            name='sharelink',
            table='share_links',
        ),
    ]
