# Generated by Django 4.1.5 on 2023-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_sharelink_options_alter_sharelink_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='redirects',
            field=models.IntegerField(default=0, verbose_name='Количество редиректов'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(max_length=30, verbose_name='Код'),
        ),
    ]
