# Generated by Django 4.1.5 on 2023-02-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0004_alter_sharelink_redirects_alter_sharelink_share_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='only_unique_redirects',
            field=models.BooleanField(default=False, verbose_name='Считать только уникальные переходы?'),
        ),
        migrations.CreateModel(
            name='LinkRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default=None, null=True, verbose_name='IP адрес')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перехода')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.sharelink', verbose_name='Ссылка')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто перешел')),
            ],
        ),
    ]
