# Generated by Django 4.1.5 on 2023-02-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_sharelink_only_unique_redirects_linkredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='share_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Истекает'),
        ),
    ]
